# Generated by Django 5.2.5 on 2025-08-26 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='owner_id_house',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
