# Generated by Django 5.2.5 on 2025-10-19 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0002_owner_owner_id_house'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField()),
                ('telefono', models.CharField()),
                ('o_id', models.IntegerField()),
            ],
        ),
    ]
