# Generated by Django 5.2.5 on 2025-10-19 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0003_baseowner'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseowner',
            name='apellido_materno',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='baseowner',
            name='apellido_paterno',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='baseowner',
            name='nombre',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='baseowner',
            name='o_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='baseowner',
            name='telefono',
            field=models.CharField(blank=True, null=True),
        ),
    ]
