# Generated by Django 5.2.5 on 2025-08-24 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='houseforsale',
            name='baths',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='houseforsale',
            name='beds',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='houseforsale',
            name='cochera',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='houseforsale',
            name='construccion',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='houseforsale',
            name='estatus',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='houseforsale',
            name='metodo_de_pago',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='houseforsale',
            name='minisplits',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='houseforsale',
            name='negociable',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='houseforsale',
            name='patio',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='houseforsale',
            name='servicios',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='houseforsale',
            name='superficie',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
