# Generated by Django 5.2.5 on 2025-09-12 01:56

import backend.storage_backends
import property.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_houseforsale_baths_houseforsale_beds_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyimage',
            name='image',
            field=models.ImageField(storage=backend.storage_backends.PrivateMediaStorage(), upload_to=property.models.property_image_upload_path),
        ),
    ]
