# Generated by Django 5.2.5 on 2025-10-19 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0002_owner_owner_id_house'),
        ('property', '0003_alter_propertyimage_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasePropertyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='BaseProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_propiedad', models.CharField(choices=[('casa', 'casa'), ('departamento', 'departamento'), ('local comercial', 'local_comercial'), ('terreno residencial', 'terreno residencial'), ('terreno rustico', 'terreno rustico'), ('terreno industrial', 'terreno industrial'), ('nave industrial', 'nave industrial'), ('bodega', 'bodega')])),
                ('titulo', models.CharField(max_length=20)),
                ('calle', models.CharField(max_length=30)),
                ('colonia', models.CharField(max_length=30)),
                ('numero', models.IntegerField()),
                ('codigo_postal', models.IntegerField()),
                ('ciudad', models.CharField(choices=[('monclova', 'monclova'), ('frontera', 'frontera'), ('castanos', 'castanos'), ('sanbuena', 'sanbuena'), ('saltillo', 'saltillo'), ('cuatrocienegas', 'cuatrocienegas')])),
                ('operacion', models.CharField(verbose_name=[('venta', 'venta'), ('renta', 'renta')])),
                ('costo', models.IntegerField()),
                ('estatus', models.CharField(choices=[('disponible', 'disponible'), ('rentada', 'rentada'), ('vendida', 'vendida')])),
                ('caracteristicas_extras', models.TextField()),
                ('comentarios', models.TextField()),
                ('tiene_cochera', models.BooleanField()),
                ('banos', models.FloatField()),
                ('acepta_mascotas', models.BooleanField()),
                ('tiene_patio', models.BooleanField()),
                ('recamaras', models.IntegerField()),
                ('centro_de_lavado', models.BooleanField()),
                ('minisplits', models.IntegerField()),
                ('servicios_incluidos', models.CharField()),
                ('numero_servicio_simas', models.CharField()),
                ('numero_servicio_cfe', models.CharField()),
                ('superficie_terreno', models.IntegerField()),
                ('superficie_construccion', models.IntegerField()),
                ('metodo_pago', models.CharField(choices=[('cualquier credito', 'cualquier credito'), ('infonavit', 'infonavit'), ('bancario', 'bancario'), ('recursos propios', 'recursos propios')])),
                ('observaciones', models.TextField()),
                ('negociable', models.BooleanField()),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owner.owner')),
            ],
        ),
    ]
