# Generated by Django 5.2.5 on 2025-10-19 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0002_owner_owner_id_house'),
        ('property', '0004_basepropertymodel_baseproperty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseproperty',
            name='acepta_mascotas',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='baseproperty',
            name='banos',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='baseproperty',
            name='calle',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='baseproperty',
            name='caracteristicas_extras',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='baseproperty',
            name='centro_de_lavado',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='baseproperty',
            name='ciudad',
            field=models.CharField(blank=True, choices=[('monclova', 'monclova'), ('frontera', 'frontera'), ('castanos', 'castanos'), ('sanbuena', 'sanbuena'), ('saltillo', 'saltillo'), ('cuatrocienegas', 'cuatrocienegas')], null=True),
        ),
        migrations.AlterField(
            model_name='baseproperty',
            name='codigo_postal',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='baseproperty',
            name='colonia',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='baseproperty',
            name='comentarios',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='baseproperty',
            name='costo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='baseproperty',
            name='estatus',
            field=models.CharField(blank=True, choices=[('disponible', 'disponible'), ('rentada', 'rentada'), ('vendida', 'vendida')], null=True),
        ),
        migrations.AlterField(
            model_name='baseproperty',
            name='metodo_pago',
            field=models.CharField(blank=True, choices=[('cualquier credito', 'cualquier credito'), ('infonavit', 'infonavit'), ('bancario', 'bancario'), ('recursos propios', 'recursos propios')], null=True),
        ),
        migrations.AlterField(
            model_name='baseproperty',
            name='minisplits',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='baseproperty',
            name='negociable',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='baseproperty',
            name='numero',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='baseproperty',
            name='numero_servicio_cfe',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='baseproperty',
            name='numero_servicio_simas',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='baseproperty',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='baseproperty',
            name='operacion',
            field=models.CharField(blank=True, null=True, verbose_name=[('venta', 'venta'), ('renta', 'renta')]),
        ),
        migrations.AlterField(
            model_name='baseproperty',
            name='propietario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='owner.owner'),
        ),
        migrations.AlterField(
            model_name='baseproperty',
            name='recamaras',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='baseproperty',
            name='servicios_incluidos',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='baseproperty',
            name='superficie_construccion',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='baseproperty',
            name='superficie_terreno',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='baseproperty',
            name='tiene_cochera',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='baseproperty',
            name='tiene_patio',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='baseproperty',
            name='tipo_propiedad',
            field=models.CharField(blank=True, choices=[('casa', 'casa'), ('departamento', 'departamento'), ('local comercial', 'local_comercial'), ('terreno residencial', 'terreno residencial'), ('terreno rustico', 'terreno rustico'), ('terreno industrial', 'terreno industrial'), ('nave industrial', 'nave industrial'), ('bodega', 'bodega')], null=True),
        ),
        migrations.AlterField(
            model_name='baseproperty',
            name='titulo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
