# Generated by Django 5.2.5 on 2025-10-26 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_alter_baseproperty_acepta_mascotas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseproperty',
            name='calle',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='baseproperty',
            name='colonia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='baseproperty',
            name='titulo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
