# Generated by Django 5.2.5 on 2025-10-26 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0004_baseowner_apellido_materno_and_more'),
        ('property', '0006_alter_baseproperty_calle_alter_baseproperty_colonia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseproperty',
            name='propietario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='owner.baseowner'),
        ),
    ]
