# Generated by Django 5.2.5 on 2025-10-26 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_alter_baseproperty_propietario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseproperty',
            name='numero',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
